name: 'Clone PSHeader'
description: 'Clone or update PSHeader repository'
inputs:
  theos_path:
    required: true
    description: 'Path to Theos installation'

runs:
  using: "composite"
  steps:
    - name: Clone PSHeader
      shell: bash
      env:
        THEOS: ${{ inputs.theos_path }}
      run: |
        if [ -d "$THEOS/include/PSHeader" ]; then
          echo "PSHeader exists. Pulling latest changes..."
          cd $THEOS/include/PSHeader
          git pull
        else
          echo "PSHeader does not exist. Cloning repository..."
          cd $THEOS/include
          git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
        fi

